import type {
  CanvasSession,
  IntentEnvelope,
  PreviewData,
} from '../types/canvas';

export const SAMPLE_THEME_CSS = `/* DO NOT EDIT — generated by Canvas */
:root {
  --dui-primary: #2563eb;
  --dui-primary-hover: #1d4ed8;
  --dui-surface: #ffffff;
  --dui-text-primary: #0f172a;
  --dui-border: #e2e8f0;
}

@media (prefers-color-scheme: dark) {
  :root {
    --dui-primary: #60a5fa;
    --dui-surface: #0f172a;
    --dui-text-primary: #f1f5f9;
  }
}
`;

export const EMPTY_SESSION: CanvasSession = {
  session_id: 'sess-empty',
  state: 'eliciting',
  messages: [],
  partial_intent: {},
};

export const ELICITING_SESSION: CanvasSession = {
  session_id: 'sess-elicit',
  state: 'eliciting',
  messages: [
    { role: 'user', content: 'Build me a logistics ops tool', timestamp: '1' },
    {
      role: 'assistant',
      content: 'Got it — what is the primary entity?',
      timestamp: '2',
    },
  ],
  partial_intent: {
    domain: 'logistics',
    aesthetic_mood: 'enterprise',
  },
};

export const COMPLETE_SESSION: CanvasSession = {
  session_id: 'sess-complete',
  state: 'complete',
  messages: [
    { role: 'user', content: 'logistics tool', timestamp: '1' },
    { role: 'assistant', content: 'Confirmed.', timestamp: '2' },
  ],
  partial_intent: {
    domain: 'logistics',
    aesthetic_mood: 'enterprise',
    operation_profile: 'read_heavy',
    density: 'standard',
    primary_entity: 'Order',
  },
};

export const COMPLETE_INTENT_ENVELOPE: IntentEnvelope = {
  state: 'complete',
  intent: COMPLETE_SESSION.partial_intent,
};

export const DASHBOARD_PREVIEW: PreviewData = {
  entity: 'Order',
  archetype: 'dashboard',
  nav_style: 'sidebar',
  theme_css: SAMPLE_THEME_CSS,
  metric_fields: ['total_value', 'shipping_cost'],
  fields: [
    {
      name: 'id',
      label: 'ID',
      display_hint: 'text',
      column_priority: 'low',
      is_status: false,
      is_monetary: false,
    },
    {
      name: 'reference',
      label: 'Reference',
      display_hint: 'text',
      column_priority: 'high',
      is_status: false,
      is_monetary: false,
    },
    {
      name: 'status',
      label: 'Status',
      display_hint: 'badge',
      column_priority: 'high',
      is_status: true,
      is_monetary: false,
    },
    {
      name: 'total_value',
      label: 'Total Value',
      display_hint: 'currency',
      column_priority: 'high',
      is_status: false,
      is_monetary: true,
    },
    {
      name: 'shipping_cost',
      label: 'Shipping',
      display_hint: 'currency',
      column_priority: 'medium',
      is_status: false,
      is_monetary: true,
    },
    {
      name: 'created_at',
      label: 'Created',
      display_hint: 'relative_time',
      column_priority: 'medium',
      is_status: false,
      is_monetary: false,
    },
  ],
  rows: [
    {
      id: 'a',
      reference: 'ORD-001',
      status: 'pending',
      total_value: 120,
      shipping_cost: 12,
      created_at: '2026-04-01',
    },
    {
      id: 'b',
      reference: 'ORD-002',
      status: 'shipped',
      total_value: 480,
      shipping_cost: 24,
      created_at: '2026-04-02',
    },
    {
      id: 'c',
      reference: 'ORD-003',
      status: 'pending',
      total_value: 300,
      shipping_cost: 18,
      created_at: '2026-04-03',
    },
  ],
};

export function withArchetype(
  archetype: PreviewData['archetype'],
): PreviewData {
  return { ...DASHBOARD_PREVIEW, archetype };
}
